theme: jekyll-theme-cayman
title: 笑草班
description: 笑草班
keywords: "blog"
url: zz19z-2021-2.github.io
permalink: /:year/:month/:day/:title/
version: 0.6.0

plugins:
    - jekyll-optional-front-matter
    - jekyll-default-layout
    - jekyll-titles-from-headings
    - jekyll-relative-links
    - jekyll-redirect-from
    - jekyll-mermaid

relative_links:
    enabled:     true
    collections: true
titles_from_headings:
    enabled:     true
    strip_title: false
    collections: false

defaults:
    - scope:
        path: "/其他/Spaces"
      values:
        layout: "space"
